# server configuration
server:
  port: 9191

# endpoint configuration
endpoints:
  shutdown:
    enabled: true

# app related configuration
mifos:
  endpoint: https://demo.openmf.org/mifosng-provider/api/v1/
  tenant: default
  authtoken: Basic bWlmb3M6cGFzc3dvcmQ=
  twilio:
    accountid: <your twilio account>
    authtoken: <your twilio auth token>
    phoneno: <your mobile no>

# message templates
message:
  template:
    createclient: Hello $name, welcome at Mifos X!
    loanrepayment: Hello $name, repayment for $account received!