# server configuration
server:
  port: 9191

# endpoint configuration
endpoints:
  shutdown:
    enabled: true

# database configuration
spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:hsqldb:file:smsmoduledb
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbcDriver

# message templates
message:
  template:
    createclient: Hello $name, welcome at Mifos X!
    loanrepayment: Hello $name, repayment for $account received!